version: '3.8'
services:
# database container
  postgresdb:
    image: postgres
    env_file:
      - .env
    networks:
      - my-network
# redis container
  redisdb:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - my-network

# service 1
  app1:
    build:
      context: ./service-2
      dockerfile: Dockerfile
    image:  nikhil382/x-tention-crew-user-service
    ports:
      - ${USER_SERVICE_REST_PORT}:${USER_SERVICE_REST_PORT}
    env_file:
      - .env
    depends_on:
      - postgresdb
      - redisdb
    restart: always
    networks:
      - my-network

# service 2
  app2:
    build:
      context: ./service-2
      dockerfile: Dockerfile
    image: nikhil382/x-tention-crew-service2
    ports:
      - ${SERVICE2_REST_PORT}:${SERVICE2_REST_PORT}
    env_file:
      - .env
    depends_on:
      - app1
    restart: always
    networks:
      - my-network

# for persistent data storage
volumes:
  redis:
  redis-config:


networks:
  my-network:
    driver: bridge